### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by keithpjolley** [seymasa/randetect#1]
```
❯ python --version; pip --version
Python 3.13.1
pip 24.3.1 from /Users/kjolley/src/venv/lib/python3.13/site-packages/pip (python 3.13)

❯ pip install randetect
Collecting randetect
  Using cached randetect-0.0.1-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: click==8.1.7 in /Users/kjolley/src/venv/lib/python3.13/site-packages (from randetect) (8.1.7)
Collecting emoji==2.8.0 (from randetect)
  Using cached emoji-2.8.0-py2.py3-none-any.whl.metadata (5.3 kB)
Collecting joblib==1.3.2 (from randetect)
  Using cached joblib-1.3.2-py3-none-any.whl.metadata (5.4 kB)
Collecting mintlemon-turkish-nlp==0.2.5 (from randetect)
  Using cached mintlemon-turkish-nlp-0.2.5.tar.gz (114 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting nltk==3.8.1 (from randetect)
  Using cached nltk-3.8.1-py3-none-any.whl.metadata (2.8 kB)
Collecting numpy==1.25.2 (from randetect)
  Using cached numpy-1.25.2.tar.gz (10.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      Traceback (most recent call last):
        File "/Users/kjolley/src/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/Users/kjolley/src/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/kjolley/src/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
        File "/Users/kjolley/src/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
        File "/usr/local/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/private/var/folders/gf/xx1d59ss1v7fcrrg8bzmhgmm0000gn/T/pip-build-env-coz8l_m5/overlay/lib/python3.13/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/private/var/folders/gf/xx1d59ss1v7fcrrg8bzmhgmm0000gn/T/pip-build-env-coz8l_m5/overlay/lib/python3.13/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/private/var/folders/gf/xx1d59ss1v7fcrrg8bzmhgmm0000gn/T/pip-build-env-coz8l_m5/overlay/lib/python3.13/site-packages/pkg_resources/__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

**Comment by keithpjolley** [comment]
d'oh.  noticed too late this was a numpy problem.  nm.
